language: node_js
node_js:
- 12
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: secret-oasis-62415
  api_key:
    secure: MgGjfJ4qfsws9XSOWzoN5adUCo415Vj2trx7IArWV2dwLDJsf2w1Tf3vyERzaz0+wRuYsUIRXngwXpAtyB5cuuP4QyxKoVXdSAWWpo8glRJHwiEHohMC28Fnchu4zYp1eBOWb84eXNB/bRSZvx2223xUHX3QQTQxlaeRqTfoGWPzTbhgMbYNHMXShzu1XGfCY1IPNSSq1fPhFBl4nZEpkWa54lhfE3Zoj0CbaJzAe8yyWs+fPAZi6uU8/xrf6xiWpWUNi8UAwfo+n+LsQoTqq+RUS2/HOCr2q7NftI7yQRhpAqM/jViVP1XijSGOf5XZ7w1wT8wd/9tgIO2SKxw4MpymdSAr0Lma/uwsXjfQ8fSevz8IFxnfVUkwiX0NlyUoKQX9kyVhTxdBvywCpsAuW4gVb4vhmAA3y/Nii/y/+3bKo7Sk+Wo/Y4WHz4djGRdNcBXMXmKf4GckV5G8ihJhv1pyPqNwqqYf9TGx2FJJUGb78lyPE8GjcjdmLy4k/BNn/RotRrg4LSI5GxzQOB5th2n5Kpoo4dZL9uzOLwTDmFJ5hHWbe5YLNWruYK26a/LqOVQF+pgyAMmGeH3J2r4AkEMdslZiQ3xY7pSmIV9dJwibyNT4Pz1Ur1wZ0uY4FyRvxW9ejhxZhghLoCkWeBAK7VSmQPXDZ9XaFF5oN31XLI4=
